package com.baqi.file;

import java.util.HashSet;
import java.util.Set;

public class Dup {
    public static void main(String[] args) {
        String[] s = new String[]{
                "/chronic/shopItem/getItemByTagId",
                "/chronic/ai/audio2Word",
                "/chronic/oss/getSign",
                "/chronic/oss/getSign",
                "/chronic/doctor/doctorInfo",
                "/chronic/familiesPatientRela/patientInfo",
                "/chronic/patient/patientInfo",
                "/chronic/familiesPatientRela/patientInfo",
                "/chronic/singleMsgList",
                "/chronic/patient/sysUser",
                "/chronic/bonusManage/doctorSendGoodsAndRead",
                "/chronic/suggestion/sugService",
                "/im/init/getInitOptions",
                "/chronic/shopItem/getDoctorItemCount",
                "/chronic/shopUserService/getUserServiceCount",
                "/chronic/shopUserService/consumeUserService",
                "/chronic/shopUserService/consumeUserService",
                "/chronic/patient/sysUser",
                "/chronic/bonusManage/doctorSendGoodsAndRead",
                "/chronic/suggestion/sugService",
                "/chronic/imdialog/listByIds",
                "/chronic/groupManage/selectByIMGroupId",
                "/im/forwardMsg/textMsg",
                "/chronic/familiesPatientRela/patients",
                "/chronic/groupDoctor/patientDoctors",
                "/chronic/shopItem/getDoctorItemCount",
                "/chronic/familiesInfo/info",
                "/im/account/batchCreate",
                "/chronic/doctor/doctorInfo",
                "/chronic/shopItem/getDoctorItem",
                "/chronic/serviceReward/queryRewardNum",
                "/chronic/shopUserService/getUserServiceCount",
                "/im/account/batchCreate",
                "/chronic/doctor/doctorInfo",
                "/chronic/bonusConfig/info",
                "/chronic/shopItem/getDoctorItem",
                "/chronic/payReward/createWxPayOrder",
                "/chronic/doctor/doctorInfo",
                "/chronic/bonusConfig/info",
                "/chronic/shopItem/getDoctorItem",
                "/chronic/payReward/createWxPayOrder",
                "/chronic/monitorStat/sportPeriodStat",
                "/chronic/measureDetail/lastDays",
                "/chronic/familiesPatientRela/patients",
                "/chronic/familiesPatientRela/selectMissRelationInfo",
                "/im/sendmsg/textMsg",
                "/chronic/dict/selectPromotionsAndBanner",
                "/chronic/healthValue/showHealthValue",
                "/chronic/familiesPatientRela/patients",
                "/chronic/measure/sendSMS",
                "/chronic/measureStatistics/last7Day",
                "/chronic/recipe/selectRecipeCount",
                "/chronic/recipe/selectDrugByPatient",
                "/chronic/measure/sendWxMsg",
                "/chronic/recipe/selectDetailById",
                "/chronic/template/info",
                "/chronic/recipe/close",
                "/chronic/template/addOrUpdate",
                "/chronic/patient/patientInfo",
                "/chronic/template/delete",
                "/chronic/recipe/selectListByPatientId",
                "/chronic/measure/healthDataAnalysis",
                "/chronic/shopItem/getDoctorItem",
                "/chronic/healthDrop/getDetaill",
                "/chronic/healthDrop/getDetaill",
                "/chronic/payReward/createWxPayOrderForOther",
                "/chronic/groupDoctor/patientDoctors",
                "/chronic/his/dischargeInfo",
                "/chronic/addIdCardNoMsg",
                "/chronic/patientTag/list",
                "/chronic/medicalRecordFiles/selectMedicalRecord",
                "/chronic/medicalRecordFiles/delete",
                "/chronic/medicalRecordFiles/saveMedicalRecord",
                "/chronic/familiesPatientRela/update",
                "/chronic/familiesPatientRela/deleteRelation",
                "/chronic/familiesInfo/info",
                "/chronic/familiesInfo/update",
                "/im/account/update",
                "/chronic/familiesInfo/info",
                "/chronic/patient/getPatientByMobile",
                "/chronic/familiesPatientRela/saveRelationByMobile",
                "/chronic/familiesPatientRela/saveOrUpdate",
                "/chronic/familiesPatientRela/saveOrUpdate",
                "/chronic/groupDoctor/patientDoctors",
                "/chronic/familiesPatientRela/saveOrUpdate",
                "/chronic/familiesPatientRela/saveOrUpdate",
                "/chronic/shopUserService/getFamiliesService",
                "/chronic/dict/selectLongPicList",
                "/chronic/payNeedLogin/createFamilyPayOrder",
                "/iot/brand/getByModel"
        };
        Set<String> set = new HashSet();
        for (int i = 0; i < s.length; i++) {
            set.add(s[i]);
        }
        System.out.println(set);
    }
}
